// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbS8b5p-YX4mW2sxF6KnligS0XQhVu7N0',
    appId: '1:1043537996250:web:943acb8f6f2997d7fef8e3',
    messagingSenderId: '1043537996250',
    projectId: 'voterapp-c47f7',
    authDomain: 'voterapp-c47f7.firebaseapp.com',
    storageBucket: 'voterapp-c47f7.appspot.com',
    measurementId: 'G-4H20JZ4R87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFpD-Rz1ISVAJBTbmrZcHkY2OxuqNrmOc',
    appId: '1:1043537996250:android:b7a772c08501a2f9fef8e3',
    messagingSenderId: '1043537996250',
    projectId: 'voterapp-c47f7',
    storageBucket: 'voterapp-c47f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnHkCYYmF76x3jAQ0a4MumWq2Df2STzZ4',
    appId: '1:1043537996250:ios:390cb234d340a29efef8e3',
    messagingSenderId: '1043537996250',
    projectId: 'voterapp-c47f7',
    storageBucket: 'voterapp-c47f7.appspot.com',
    iosBundleId: 'com.example.votingApp',
  );
}
